### ISSUE TITLE
你好，请问这个主题怎么在（小康博客标题下面）添加今日诗词调用

### ISSUE THREAD

**Issue by muzhi621** [DreamyTZK/Static_butterfly#2]
![image](https://user-images.githubusercontent.com/41742756/109500163-d2010300-7ad0-11eb-8fcd-37118c0ef4dc.png)

**Comment by DreamyTZK** [comment]
@muzhi621 移步[https://github.com/jerryc127/hexo-theme-butterfly](https://github.com/jerryc127/hexo-theme-butterfly)
